[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "automata"
version = "0.1.0"
description = "Automatically generate course webpages from annotated materials."
authors = [
    { name = "Justin Eldridge", email = "jeldridge@ucsd.edu" }
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pyyaml", "jinja2", "markdown"
]
