"""Hooks system for automata."""

from ._definitions import (
    BuildArtifactHookArgs,
    BuildArtifactSuccessHookArgs,
    BuildHooks,
    BuildMaterialsNodeHookArgs,
    DiscoverHookArgs,
    DiscoverHooks,
    ExportCopyHookArgs,
    ExportHooks,
    ExportNodeHookArgs,
    FilterHookArgs,
    FilterHooks,
    Hooks,
    PublisherRegistryArgs,
    PublishHooks,
    PublishPostHookArgs,
    PublishPreHookArgs,
    RenderExtraPagesHookArgs,
    RenderHooks,
    RenderPostHookArgs,
    RenderPreHookArgs,
    WebsiteInputs,
)

__all__ = [
    "BuildArtifactHookArgs",
    "BuildHooks",
    "BuildMaterialsNodeHookArgs",
    "BuildArtifactSuccessHookArgs",
    "DiscoverHookArgs",
    "DiscoverHooks",
    "ExportCopyHookArgs",
    "ExportHooks",
    "ExportNodeHookArgs",
    "FilterHookArgs",
    "FilterHooks",
    "RenderHooks",
    "RenderPostHookArgs",
    "RenderExtraPagesHookArgs",
    "Hooks",
    "PublishHooks",
    "PublishPostHookArgs",
    "PublishPreHookArgs",
    "PublisherRegistryArgs",
    "RenderPreHookArgs",
    "WebsiteInputs",
]
