"""Hooks system for automata."""

from ._definitions import (
    BuildArtifactHookArgs,
    BuildHooks,
    BuildNodeHookArgs,
    BuildSuccessHookArgs,
    DiscoverHookArgs,
    DiscoverHooks,
    ExportCopyHookArgs,
    ExportHooks,
    ExportNodeHookArgs,
    FilterHookArgs,
    FilterHooks,
    GenerateHooks,
    GeneratePostHookArgs,
    GeneratePreHookArgs,
    Hooks,
    PublishHooks,
    PublishPostHookArgs,
    PublishPreHookArgs,
    PublisherRegistryArgs,
    WebsiteGeneratePreHookArgs,
    WebsiteInputs,
)

__all__ = [
    "BuildArtifactHookArgs",
    "BuildHooks",
    "BuildNodeHookArgs",
    "BuildSuccessHookArgs",
    "DiscoverHookArgs",
    "DiscoverHooks",
    "ExportCopyHookArgs",
    "ExportHooks",
    "ExportNodeHookArgs",
    "FilterHookArgs",
    "FilterHooks",
    "GenerateHooks",
    "GeneratePostHookArgs",
    "GeneratePreHookArgs",
    "Hooks",
    "PublishHooks",
    "PublishPostHookArgs",
    "PublishPreHookArgs",
    "PublisherRegistryArgs",
    "WebsiteGeneratePreHookArgs",
    "WebsiteInputs",
]
